# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contratos_grpc import frota_pb2 as contratos__grpc_dot_frota__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contratos_grpc/frota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoGestaoVeiculosStub:
    """SERVIÇOS gRPC 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObterVeiculo = channel.unary_unary(
                '/frota.ServicoGestaoVeiculos/ObterVeiculo',
                request_serializer=contratos__grpc_dot_frota__pb2.RequisicaoObterVeiculoPorId.SerializeToString,
                response_deserializer=contratos__grpc_dot_frota__pb2.Veiculo.FromString,
                _registered_method=True)
        self.ListarVeiculos = channel.unary_unary(
                '/frota.ServicoGestaoVeiculos/ListarVeiculos',
                request_serializer=contratos__grpc_dot_frota__pb2.RequisicaoListarVeiculos.SerializeToString,
                response_deserializer=contratos__grpc_dot_frota__pb2.RespostaListaVeiculos.FromString,
                _registered_method=True)


class ServicoGestaoVeiculosServicer:
    """SERVIÇOS gRPC 

    """

    def ObterVeiculo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarVeiculos(self, request, context):
        """(Omiti os métodos de Criar/Atualizar para não deixar o arquivo gigante, 
        mas podemos adicionar depois se o Gateway for suportar operações de Admin)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoGestaoVeiculosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObterVeiculo': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterVeiculo,
                    request_deserializer=contratos__grpc_dot_frota__pb2.RequisicaoObterVeiculoPorId.FromString,
                    response_serializer=contratos__grpc_dot_frota__pb2.Veiculo.SerializeToString,
            ),
            'ListarVeiculos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarVeiculos,
                    request_deserializer=contratos__grpc_dot_frota__pb2.RequisicaoListarVeiculos.FromString,
                    response_serializer=contratos__grpc_dot_frota__pb2.RespostaListaVeiculos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frota.ServicoGestaoVeiculos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('frota.ServicoGestaoVeiculos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoGestaoVeiculos:
    """SERVIÇOS gRPC 

    """

    @staticmethod
    def ObterVeiculo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frota.ServicoGestaoVeiculos/ObterVeiculo',
            contratos__grpc_dot_frota__pb2.RequisicaoObterVeiculoPorId.SerializeToString,
            contratos__grpc_dot_frota__pb2.Veiculo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarVeiculos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frota.ServicoGestaoVeiculos/ListarVeiculos',
            contratos__grpc_dot_frota__pb2.RequisicaoListarVeiculos.SerializeToString,
            contratos__grpc_dot_frota__pb2.RespostaListaVeiculos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServicoGestaoReservasStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimularReserva = channel.unary_unary(
                '/frota.ServicoGestaoReservas/SimularReserva',
                request_serializer=contratos__grpc_dot_frota__pb2.RequisicaoSimularReserva.SerializeToString,
                response_deserializer=contratos__grpc_dot_frota__pb2.RespostaSimularReserva.FromString,
                _registered_method=True)
        self.CriarReserva = channel.unary_unary(
                '/frota.ServicoGestaoReservas/CriarReserva',
                request_serializer=contratos__grpc_dot_frota__pb2.RequisicaoCriarReserva.SerializeToString,
                response_deserializer=contratos__grpc_dot_frota__pb2.Reserva.FromString,
                _registered_method=True)


class ServicoGestaoReservasServicer:
    """Missing associated documentation comment in .proto file."""

    def SimularReserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarReserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoGestaoReservasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimularReserva': grpc.unary_unary_rpc_method_handler(
                    servicer.SimularReserva,
                    request_deserializer=contratos__grpc_dot_frota__pb2.RequisicaoSimularReserva.FromString,
                    response_serializer=contratos__grpc_dot_frota__pb2.RespostaSimularReserva.SerializeToString,
            ),
            'CriarReserva': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarReserva,
                    request_deserializer=contratos__grpc_dot_frota__pb2.RequisicaoCriarReserva.FromString,
                    response_serializer=contratos__grpc_dot_frota__pb2.Reserva.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frota.ServicoGestaoReservas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('frota.ServicoGestaoReservas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoGestaoReservas:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimularReserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frota.ServicoGestaoReservas/SimularReserva',
            contratos__grpc_dot_frota__pb2.RequisicaoSimularReserva.SerializeToString,
            contratos__grpc_dot_frota__pb2.RespostaSimularReserva.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarReserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frota.ServicoGestaoReservas/CriarReserva',
            contratos__grpc_dot_frota__pb2.RequisicaoCriarReserva.SerializeToString,
            contratos__grpc_dot_frota__pb2.Reserva.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
