// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: autenticacao.proto

#include "autenticacao.pb.h"
#include "autenticacao.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace autenticacao {

static const char* ServicoAutenticacao_method_names[] = {
  "/autenticacao.ServicoAutenticacao/Login",
  "/autenticacao.ServicoAutenticacao/ValidarToken",
};

std::unique_ptr< ServicoAutenticacao::Stub> ServicoAutenticacao::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServicoAutenticacao::Stub> stub(new ServicoAutenticacao::Stub(channel, options));
  return stub;
}

ServicoAutenticacao::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(ServicoAutenticacao_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ValidarToken_(ServicoAutenticacao_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServicoAutenticacao::Stub::Login(::grpc::ClientContext* context, const ::autenticacao::RequisicaoLogin& request, ::autenticacao::RespostaToken* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoLogin, ::autenticacao::RespostaToken, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void ServicoAutenticacao::Stub::async::Login(::grpc::ClientContext* context, const ::autenticacao::RequisicaoLogin* request, ::autenticacao::RespostaToken* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoLogin, ::autenticacao::RespostaToken, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void ServicoAutenticacao::Stub::async::Login(::grpc::ClientContext* context, const ::autenticacao::RequisicaoLogin* request, ::autenticacao::RespostaToken* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::RespostaToken>* ServicoAutenticacao::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoLogin& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::RespostaToken, ::autenticacao::RequisicaoLogin, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::RespostaToken>* ServicoAutenticacao::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoLogin& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoAutenticacao::Stub::ValidarToken(::grpc::ClientContext* context, const ::autenticacao::RequisicaoValidarToken& request, ::autenticacao::RespostaValidacao* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoValidarToken, ::autenticacao::RespostaValidacao, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ValidarToken_, context, request, response);
}

void ServicoAutenticacao::Stub::async::ValidarToken(::grpc::ClientContext* context, const ::autenticacao::RequisicaoValidarToken* request, ::autenticacao::RespostaValidacao* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoValidarToken, ::autenticacao::RespostaValidacao, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidarToken_, context, request, response, std::move(f));
}

void ServicoAutenticacao::Stub::async::ValidarToken(::grpc::ClientContext* context, const ::autenticacao::RequisicaoValidarToken* request, ::autenticacao::RespostaValidacao* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidarToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::RespostaValidacao>* ServicoAutenticacao::Stub::PrepareAsyncValidarTokenRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoValidarToken& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::RespostaValidacao, ::autenticacao::RequisicaoValidarToken, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ValidarToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::RespostaValidacao>* ServicoAutenticacao::Stub::AsyncValidarTokenRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoValidarToken& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidarTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServicoAutenticacao::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoAutenticacao_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoAutenticacao::Service, ::autenticacao::RequisicaoLogin, ::autenticacao::RespostaToken, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoAutenticacao::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoLogin* req,
             ::autenticacao::RespostaToken* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoAutenticacao_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoAutenticacao::Service, ::autenticacao::RequisicaoValidarToken, ::autenticacao::RespostaValidacao, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoAutenticacao::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoValidarToken* req,
             ::autenticacao::RespostaValidacao* resp) {
               return service->ValidarToken(ctx, req, resp);
             }, this)));
}

ServicoAutenticacao::Service::~Service() {
}

::grpc::Status ServicoAutenticacao::Service::Login(::grpc::ServerContext* context, const ::autenticacao::RequisicaoLogin* request, ::autenticacao::RespostaToken* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoAutenticacao::Service::ValidarToken(::grpc::ServerContext* context, const ::autenticacao::RequisicaoValidarToken* request, ::autenticacao::RespostaValidacao* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ServicoFuncionario_method_names[] = {
  "/autenticacao.ServicoFuncionario/CriarFuncionario",
  "/autenticacao.ServicoFuncionario/ObterFuncionario",
};

std::unique_ptr< ServicoFuncionario::Stub> ServicoFuncionario::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServicoFuncionario::Stub> stub(new ServicoFuncionario::Stub(channel, options));
  return stub;
}

ServicoFuncionario::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CriarFuncionario_(ServicoFuncionario_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ObterFuncionario_(ServicoFuncionario_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServicoFuncionario::Stub::CriarFuncionario(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarFuncionario& request, ::autenticacao::Funcionario* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoCriarFuncionario, ::autenticacao::Funcionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CriarFuncionario_, context, request, response);
}

void ServicoFuncionario::Stub::async::CriarFuncionario(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarFuncionario* request, ::autenticacao::Funcionario* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoCriarFuncionario, ::autenticacao::Funcionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarFuncionario_, context, request, response, std::move(f));
}

void ServicoFuncionario::Stub::async::CriarFuncionario(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarFuncionario* request, ::autenticacao::Funcionario* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarFuncionario_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::Funcionario>* ServicoFuncionario::Stub::PrepareAsyncCriarFuncionarioRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarFuncionario& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::Funcionario, ::autenticacao::RequisicaoCriarFuncionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CriarFuncionario_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::Funcionario>* ServicoFuncionario::Stub::AsyncCriarFuncionarioRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarFuncionario& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCriarFuncionarioRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoFuncionario::Stub::ObterFuncionario(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::autenticacao::Funcionario* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoObterPorId, ::autenticacao::Funcionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ObterFuncionario_, context, request, response);
}

void ServicoFuncionario::Stub::async::ObterFuncionario(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::Funcionario* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoObterPorId, ::autenticacao::Funcionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterFuncionario_, context, request, response, std::move(f));
}

void ServicoFuncionario::Stub::async::ObterFuncionario(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::Funcionario* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterFuncionario_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::Funcionario>* ServicoFuncionario::Stub::PrepareAsyncObterFuncionarioRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::Funcionario, ::autenticacao::RequisicaoObterPorId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ObterFuncionario_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::Funcionario>* ServicoFuncionario::Stub::AsyncObterFuncionarioRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncObterFuncionarioRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServicoFuncionario::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoFuncionario_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoFuncionario::Service, ::autenticacao::RequisicaoCriarFuncionario, ::autenticacao::Funcionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoFuncionario::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoCriarFuncionario* req,
             ::autenticacao::Funcionario* resp) {
               return service->CriarFuncionario(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoFuncionario_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoFuncionario::Service, ::autenticacao::RequisicaoObterPorId, ::autenticacao::Funcionario, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoFuncionario::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoObterPorId* req,
             ::autenticacao::Funcionario* resp) {
               return service->ObterFuncionario(ctx, req, resp);
             }, this)));
}

ServicoFuncionario::Service::~Service() {
}

::grpc::Status ServicoFuncionario::Service::CriarFuncionario(::grpc::ServerContext* context, const ::autenticacao::RequisicaoCriarFuncionario* request, ::autenticacao::Funcionario* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoFuncionario::Service::ObterFuncionario(::grpc::ServerContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::Funcionario* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ServicoCliente_method_names[] = {
  "/autenticacao.ServicoCliente/CriarPessoaFisica",
  "/autenticacao.ServicoCliente/CriarPessoaJuridica",
  "/autenticacao.ServicoCliente/ObterPessoaFisica",
  "/autenticacao.ServicoCliente/ObterPessoaJuridica",
  "/autenticacao.ServicoCliente/AssociarMotorista",
};

std::unique_ptr< ServicoCliente::Stub> ServicoCliente::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServicoCliente::Stub> stub(new ServicoCliente::Stub(channel, options));
  return stub;
}

ServicoCliente::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CriarPessoaFisica_(ServicoCliente_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CriarPessoaJuridica_(ServicoCliente_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ObterPessoaFisica_(ServicoCliente_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ObterPessoaJuridica_(ServicoCliente_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AssociarMotorista_(ServicoCliente_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServicoCliente::Stub::CriarPessoaFisica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaFisica& request, ::autenticacao::PessoaFisica* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoCriarPessoaFisica, ::autenticacao::PessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CriarPessoaFisica_, context, request, response);
}

void ServicoCliente::Stub::async::CriarPessoaFisica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaFisica* request, ::autenticacao::PessoaFisica* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoCriarPessoaFisica, ::autenticacao::PessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarPessoaFisica_, context, request, response, std::move(f));
}

void ServicoCliente::Stub::async::CriarPessoaFisica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaFisica* request, ::autenticacao::PessoaFisica* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarPessoaFisica_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaFisica>* ServicoCliente::Stub::PrepareAsyncCriarPessoaFisicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaFisica& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::PessoaFisica, ::autenticacao::RequisicaoCriarPessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CriarPessoaFisica_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaFisica>* ServicoCliente::Stub::AsyncCriarPessoaFisicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaFisica& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCriarPessoaFisicaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoCliente::Stub::CriarPessoaJuridica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaJuridica& request, ::autenticacao::PessoaJuridica* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoCriarPessoaJuridica, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CriarPessoaJuridica_, context, request, response);
}

void ServicoCliente::Stub::async::CriarPessoaJuridica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaJuridica* request, ::autenticacao::PessoaJuridica* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoCriarPessoaJuridica, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarPessoaJuridica_, context, request, response, std::move(f));
}

void ServicoCliente::Stub::async::CriarPessoaJuridica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaJuridica* request, ::autenticacao::PessoaJuridica* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarPessoaJuridica_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaJuridica>* ServicoCliente::Stub::PrepareAsyncCriarPessoaJuridicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaJuridica& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::PessoaJuridica, ::autenticacao::RequisicaoCriarPessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CriarPessoaJuridica_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaJuridica>* ServicoCliente::Stub::AsyncCriarPessoaJuridicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoCriarPessoaJuridica& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCriarPessoaJuridicaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoCliente::Stub::ObterPessoaFisica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::autenticacao::PessoaFisica* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoObterPorId, ::autenticacao::PessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ObterPessoaFisica_, context, request, response);
}

void ServicoCliente::Stub::async::ObterPessoaFisica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::PessoaFisica* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoObterPorId, ::autenticacao::PessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterPessoaFisica_, context, request, response, std::move(f));
}

void ServicoCliente::Stub::async::ObterPessoaFisica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::PessoaFisica* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterPessoaFisica_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaFisica>* ServicoCliente::Stub::PrepareAsyncObterPessoaFisicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::PessoaFisica, ::autenticacao::RequisicaoObterPorId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ObterPessoaFisica_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaFisica>* ServicoCliente::Stub::AsyncObterPessoaFisicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncObterPessoaFisicaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoCliente::Stub::ObterPessoaJuridica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::autenticacao::PessoaJuridica* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoObterPorId, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ObterPessoaJuridica_, context, request, response);
}

void ServicoCliente::Stub::async::ObterPessoaJuridica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::PessoaJuridica* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoObterPorId, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterPessoaJuridica_, context, request, response, std::move(f));
}

void ServicoCliente::Stub::async::ObterPessoaJuridica(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::PessoaJuridica* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterPessoaJuridica_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaJuridica>* ServicoCliente::Stub::PrepareAsyncObterPessoaJuridicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::PessoaJuridica, ::autenticacao::RequisicaoObterPorId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ObterPessoaJuridica_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaJuridica>* ServicoCliente::Stub::AsyncObterPessoaJuridicaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoObterPorId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncObterPessoaJuridicaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoCliente::Stub::AssociarMotorista(::grpc::ClientContext* context, const ::autenticacao::RequisicaoAssociarMotorista& request, ::autenticacao::PessoaJuridica* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autenticacao::RequisicaoAssociarMotorista, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AssociarMotorista_, context, request, response);
}

void ServicoCliente::Stub::async::AssociarMotorista(::grpc::ClientContext* context, const ::autenticacao::RequisicaoAssociarMotorista* request, ::autenticacao::PessoaJuridica* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autenticacao::RequisicaoAssociarMotorista, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssociarMotorista_, context, request, response, std::move(f));
}

void ServicoCliente::Stub::async::AssociarMotorista(::grpc::ClientContext* context, const ::autenticacao::RequisicaoAssociarMotorista* request, ::autenticacao::PessoaJuridica* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssociarMotorista_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaJuridica>* ServicoCliente::Stub::PrepareAsyncAssociarMotoristaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoAssociarMotorista& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autenticacao::PessoaJuridica, ::autenticacao::RequisicaoAssociarMotorista, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AssociarMotorista_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autenticacao::PessoaJuridica>* ServicoCliente::Stub::AsyncAssociarMotoristaRaw(::grpc::ClientContext* context, const ::autenticacao::RequisicaoAssociarMotorista& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAssociarMotoristaRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServicoCliente::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoCliente_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoCliente::Service, ::autenticacao::RequisicaoCriarPessoaFisica, ::autenticacao::PessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoCliente::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoCriarPessoaFisica* req,
             ::autenticacao::PessoaFisica* resp) {
               return service->CriarPessoaFisica(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoCliente_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoCliente::Service, ::autenticacao::RequisicaoCriarPessoaJuridica, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoCliente::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoCriarPessoaJuridica* req,
             ::autenticacao::PessoaJuridica* resp) {
               return service->CriarPessoaJuridica(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoCliente_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoCliente::Service, ::autenticacao::RequisicaoObterPorId, ::autenticacao::PessoaFisica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoCliente::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoObterPorId* req,
             ::autenticacao::PessoaFisica* resp) {
               return service->ObterPessoaFisica(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoCliente_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoCliente::Service, ::autenticacao::RequisicaoObterPorId, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoCliente::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoObterPorId* req,
             ::autenticacao::PessoaJuridica* resp) {
               return service->ObterPessoaJuridica(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoCliente_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoCliente::Service, ::autenticacao::RequisicaoAssociarMotorista, ::autenticacao::PessoaJuridica, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoCliente::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autenticacao::RequisicaoAssociarMotorista* req,
             ::autenticacao::PessoaJuridica* resp) {
               return service->AssociarMotorista(ctx, req, resp);
             }, this)));
}

ServicoCliente::Service::~Service() {
}

::grpc::Status ServicoCliente::Service::CriarPessoaFisica(::grpc::ServerContext* context, const ::autenticacao::RequisicaoCriarPessoaFisica* request, ::autenticacao::PessoaFisica* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoCliente::Service::CriarPessoaJuridica(::grpc::ServerContext* context, const ::autenticacao::RequisicaoCriarPessoaJuridica* request, ::autenticacao::PessoaJuridica* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoCliente::Service::ObterPessoaFisica(::grpc::ServerContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::PessoaFisica* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoCliente::Service::ObterPessoaJuridica(::grpc::ServerContext* context, const ::autenticacao::RequisicaoObterPorId* request, ::autenticacao::PessoaJuridica* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoCliente::Service::AssociarMotorista(::grpc::ServerContext* context, const ::autenticacao::RequisicaoAssociarMotorista* request, ::autenticacao::PessoaJuridica* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace autenticacao

