// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: frota.proto
#ifndef GRPC_frota_2eproto__INCLUDED
#define GRPC_frota_2eproto__INCLUDED

#include "frota.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace frota {

// SERVIÇOS gRPC 
//
class ServicoGestaoVeiculos final {
 public:
  static constexpr char const* service_full_name() {
    return "frota.ServicoGestaoVeiculos";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::frota::Veiculo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Veiculo>> AsyncObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Veiculo>>(AsyncObterVeiculoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Veiculo>> PrepareAsyncObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Veiculo>>(PrepareAsyncObterVeiculoRaw(context, request, cq));
    }
    virtual ::grpc::Status ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::frota::RespostaListaVeiculos* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaListaVeiculos>> AsyncListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaListaVeiculos>>(AsyncListarVeiculosRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaListaVeiculos>> PrepareAsyncListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaListaVeiculos>>(PrepareAsyncListarVeiculosRaw(context, request, cq));
    }
    // (Omiti os métodos de Criar/Atualizar para não deixar o arquivo gigante, 
    // mas podemos adicionar depois se o Gateway for suportar operações de Admin)
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // (Omiti os métodos de Criar/Atualizar para não deixar o arquivo gigante, 
      // mas podemos adicionar depois se o Gateway for suportar operações de Admin)
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::Veiculo>* AsyncObterVeiculoRaw(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::Veiculo>* PrepareAsyncObterVeiculoRaw(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaListaVeiculos>* AsyncListarVeiculosRaw(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaListaVeiculos>* PrepareAsyncListarVeiculosRaw(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::frota::Veiculo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Veiculo>> AsyncObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Veiculo>>(AsyncObterVeiculoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Veiculo>> PrepareAsyncObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Veiculo>>(PrepareAsyncObterVeiculoRaw(context, request, cq));
    }
    ::grpc::Status ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::frota::RespostaListaVeiculos* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>> AsyncListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>>(AsyncListarVeiculosRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>> PrepareAsyncListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>>(PrepareAsyncListarVeiculosRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response, std::function<void(::grpc::Status)>) override;
      void ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response, std::function<void(::grpc::Status)>) override;
      void ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::frota::Veiculo>* AsyncObterVeiculoRaw(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frota::Veiculo>* PrepareAsyncObterVeiculoRaw(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>* AsyncListarVeiculosRaw(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>* PrepareAsyncListarVeiculosRaw(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ObterVeiculo_;
    const ::grpc::internal::RpcMethod rpcmethod_ListarVeiculos_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ObterVeiculo(::grpc::ServerContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response);
    virtual ::grpc::Status ListarVeiculos(::grpc::ServerContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response);
    // (Omiti os métodos de Criar/Atualizar para não deixar o arquivo gigante, 
    // mas podemos adicionar depois se o Gateway for suportar operações de Admin)
  };
  template <class BaseClass>
  class WithAsyncMethod_ObterVeiculo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ObterVeiculo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ObterVeiculo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterVeiculo(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestObterVeiculo(::grpc::ServerContext* context, ::frota::RequisicaoObterVeiculoPorId* request, ::grpc::ServerAsyncResponseWriter< ::frota::Veiculo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListarVeiculos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListarVeiculos() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListarVeiculos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListarVeiculos(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListarVeiculos(::grpc::ServerContext* context, ::frota::RequisicaoListarVeiculos* request, ::grpc::ServerAsyncResponseWriter< ::frota::RespostaListaVeiculos>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ObterVeiculo<WithAsyncMethod_ListarVeiculos<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ObterVeiculo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ObterVeiculo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response) { return this->ObterVeiculo(context, request, response); }));}
    void SetMessageAllocatorFor_ObterVeiculo(
        ::grpc::MessageAllocator< ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ObterVeiculo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterVeiculo(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ObterVeiculo(
      ::grpc::CallbackServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListarVeiculos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListarVeiculos() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response) { return this->ListarVeiculos(context, request, response); }));}
    void SetMessageAllocatorFor_ListarVeiculos(
        ::grpc::MessageAllocator< ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListarVeiculos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListarVeiculos(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListarVeiculos(
      ::grpc::CallbackServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ObterVeiculo<WithCallbackMethod_ListarVeiculos<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ObterVeiculo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ObterVeiculo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ObterVeiculo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterVeiculo(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListarVeiculos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListarVeiculos() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListarVeiculos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListarVeiculos(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ObterVeiculo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ObterVeiculo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ObterVeiculo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterVeiculo(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestObterVeiculo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListarVeiculos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListarVeiculos() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListarVeiculos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListarVeiculos(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListarVeiculos(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ObterVeiculo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ObterVeiculo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ObterVeiculo(context, request, response); }));
    }
    ~WithRawCallbackMethod_ObterVeiculo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterVeiculo(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ObterVeiculo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListarVeiculos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListarVeiculos() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListarVeiculos(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListarVeiculos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListarVeiculos(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListarVeiculos(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ObterVeiculo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ObterVeiculo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo>* streamer) {
                       return this->StreamedObterVeiculo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ObterVeiculo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ObterVeiculo(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoObterVeiculoPorId* /*request*/, ::frota::Veiculo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedObterVeiculo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::frota::RequisicaoObterVeiculoPorId,::frota::Veiculo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListarVeiculos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListarVeiculos() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos>* streamer) {
                       return this->StreamedListarVeiculos(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListarVeiculos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListarVeiculos(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoListarVeiculos* /*request*/, ::frota::RespostaListaVeiculos* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListarVeiculos(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::frota::RequisicaoListarVeiculos,::frota::RespostaListaVeiculos>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ObterVeiculo<WithStreamedUnaryMethod_ListarVeiculos<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ObterVeiculo<WithStreamedUnaryMethod_ListarVeiculos<Service > > StreamedService;
};

class ServicoGestaoReservas final {
 public:
  static constexpr char const* service_full_name() {
    return "frota.ServicoGestaoReservas";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::frota::RespostaSimularReserva* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaSimularReserva>> AsyncSimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaSimularReserva>>(AsyncSimularReservaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaSimularReserva>> PrepareAsyncSimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaSimularReserva>>(PrepareAsyncSimularReservaRaw(context, request, cq));
    }
    virtual ::grpc::Status CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::frota::Reserva* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Reserva>> AsyncCriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Reserva>>(AsyncCriarReservaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Reserva>> PrepareAsyncCriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frota::Reserva>>(PrepareAsyncCriarReservaRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaSimularReserva>* AsyncSimularReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::RespostaSimularReserva>* PrepareAsyncSimularReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::Reserva>* AsyncCriarReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frota::Reserva>* PrepareAsyncCriarReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::frota::RespostaSimularReserva* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>> AsyncSimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>>(AsyncSimularReservaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>> PrepareAsyncSimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>>(PrepareAsyncSimularReservaRaw(context, request, cq));
    }
    ::grpc::Status CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::frota::Reserva* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Reserva>> AsyncCriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Reserva>>(AsyncCriarReservaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Reserva>> PrepareAsyncCriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frota::Reserva>>(PrepareAsyncCriarReservaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response, std::function<void(::grpc::Status)>) override;
      void SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response, std::function<void(::grpc::Status)>) override;
      void CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>* AsyncSimularReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>* PrepareAsyncSimularReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frota::Reserva>* AsyncCriarReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frota::Reserva>* PrepareAsyncCriarReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SimularReserva_;
    const ::grpc::internal::RpcMethod rpcmethod_CriarReserva_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SimularReserva(::grpc::ServerContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response);
    virtual ::grpc::Status CriarReserva(::grpc::ServerContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SimularReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SimularReserva() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SimularReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SimularReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSimularReserva(::grpc::ServerContext* context, ::frota::RequisicaoSimularReserva* request, ::grpc::ServerAsyncResponseWriter< ::frota::RespostaSimularReserva>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CriarReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CriarReserva() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CriarReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CriarReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCriarReserva(::grpc::ServerContext* context, ::frota::RequisicaoCriarReserva* request, ::grpc::ServerAsyncResponseWriter< ::frota::Reserva>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SimularReserva<WithAsyncMethod_CriarReserva<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SimularReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SimularReserva() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response) { return this->SimularReserva(context, request, response); }));}
    void SetMessageAllocatorFor_SimularReserva(
        ::grpc::MessageAllocator< ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SimularReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SimularReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SimularReserva(
      ::grpc::CallbackServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CriarReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CriarReserva() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoCriarReserva, ::frota::Reserva>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response) { return this->CriarReserva(context, request, response); }));}
    void SetMessageAllocatorFor_CriarReserva(
        ::grpc::MessageAllocator< ::frota::RequisicaoCriarReserva, ::frota::Reserva>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::frota::RequisicaoCriarReserva, ::frota::Reserva>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CriarReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CriarReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CriarReserva(
      ::grpc::CallbackServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SimularReserva<WithCallbackMethod_CriarReserva<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SimularReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SimularReserva() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SimularReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SimularReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CriarReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CriarReserva() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CriarReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CriarReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SimularReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SimularReserva() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SimularReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SimularReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSimularReserva(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CriarReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CriarReserva() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CriarReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CriarReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCriarReserva(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SimularReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SimularReserva() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SimularReserva(context, request, response); }));
    }
    ~WithRawCallbackMethod_SimularReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SimularReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SimularReserva(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CriarReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CriarReserva() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CriarReserva(context, request, response); }));
    }
    ~WithRawCallbackMethod_CriarReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CriarReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CriarReserva(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SimularReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SimularReserva() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva>* streamer) {
                       return this->StreamedSimularReserva(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SimularReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SimularReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoSimularReserva* /*request*/, ::frota::RespostaSimularReserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSimularReserva(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::frota::RequisicaoSimularReserva,::frota::RespostaSimularReserva>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CriarReserva : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CriarReserva() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::frota::RequisicaoCriarReserva, ::frota::Reserva>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::frota::RequisicaoCriarReserva, ::frota::Reserva>* streamer) {
                       return this->StreamedCriarReserva(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CriarReserva() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CriarReserva(::grpc::ServerContext* /*context*/, const ::frota::RequisicaoCriarReserva* /*request*/, ::frota::Reserva* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCriarReserva(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::frota::RequisicaoCriarReserva,::frota::Reserva>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SimularReserva<WithStreamedUnaryMethod_CriarReserva<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SimularReserva<WithStreamedUnaryMethod_CriarReserva<Service > > StreamedService;
};

}  // namespace frota


#endif  // GRPC_frota_2eproto__INCLUDED
