// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: frota.proto

#include "frota.pb.h"
#include "frota.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace frota {

static const char* ServicoGestaoVeiculos_method_names[] = {
  "/frota.ServicoGestaoVeiculos/ObterVeiculo",
  "/frota.ServicoGestaoVeiculos/ListarVeiculos",
};

std::unique_ptr< ServicoGestaoVeiculos::Stub> ServicoGestaoVeiculos::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServicoGestaoVeiculos::Stub> stub(new ServicoGestaoVeiculos::Stub(channel, options));
  return stub;
}

ServicoGestaoVeiculos::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ObterVeiculo_(ServicoGestaoVeiculos_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListarVeiculos_(ServicoGestaoVeiculos_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServicoGestaoVeiculos::Stub::ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::frota::Veiculo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ObterVeiculo_, context, request, response);
}

void ServicoGestaoVeiculos::Stub::async::ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterVeiculo_, context, request, response, std::move(f));
}

void ServicoGestaoVeiculos::Stub::async::ObterVeiculo(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ObterVeiculo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::frota::Veiculo>* ServicoGestaoVeiculos::Stub::PrepareAsyncObterVeiculoRaw(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::frota::Veiculo, ::frota::RequisicaoObterVeiculoPorId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ObterVeiculo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::frota::Veiculo>* ServicoGestaoVeiculos::Stub::AsyncObterVeiculoRaw(::grpc::ClientContext* context, const ::frota::RequisicaoObterVeiculoPorId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncObterVeiculoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoGestaoVeiculos::Stub::ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::frota::RespostaListaVeiculos* response) {
  return ::grpc::internal::BlockingUnaryCall< ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListarVeiculos_, context, request, response);
}

void ServicoGestaoVeiculos::Stub::async::ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListarVeiculos_, context, request, response, std::move(f));
}

void ServicoGestaoVeiculos::Stub::async::ListarVeiculos(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListarVeiculos_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>* ServicoGestaoVeiculos::Stub::PrepareAsyncListarVeiculosRaw(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::frota::RespostaListaVeiculos, ::frota::RequisicaoListarVeiculos, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListarVeiculos_, context, request);
}

::grpc::ClientAsyncResponseReader< ::frota::RespostaListaVeiculos>* ServicoGestaoVeiculos::Stub::AsyncListarVeiculosRaw(::grpc::ClientContext* context, const ::frota::RequisicaoListarVeiculos& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListarVeiculosRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServicoGestaoVeiculos::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoGestaoVeiculos_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoGestaoVeiculos::Service, ::frota::RequisicaoObterVeiculoPorId, ::frota::Veiculo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoGestaoVeiculos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::frota::RequisicaoObterVeiculoPorId* req,
             ::frota::Veiculo* resp) {
               return service->ObterVeiculo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoGestaoVeiculos_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoGestaoVeiculos::Service, ::frota::RequisicaoListarVeiculos, ::frota::RespostaListaVeiculos, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoGestaoVeiculos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::frota::RequisicaoListarVeiculos* req,
             ::frota::RespostaListaVeiculos* resp) {
               return service->ListarVeiculos(ctx, req, resp);
             }, this)));
}

ServicoGestaoVeiculos::Service::~Service() {
}

::grpc::Status ServicoGestaoVeiculos::Service::ObterVeiculo(::grpc::ServerContext* context, const ::frota::RequisicaoObterVeiculoPorId* request, ::frota::Veiculo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoGestaoVeiculos::Service::ListarVeiculos(::grpc::ServerContext* context, const ::frota::RequisicaoListarVeiculos* request, ::frota::RespostaListaVeiculos* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ServicoGestaoReservas_method_names[] = {
  "/frota.ServicoGestaoReservas/SimularReserva",
  "/frota.ServicoGestaoReservas/CriarReserva",
};

std::unique_ptr< ServicoGestaoReservas::Stub> ServicoGestaoReservas::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServicoGestaoReservas::Stub> stub(new ServicoGestaoReservas::Stub(channel, options));
  return stub;
}

ServicoGestaoReservas::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SimularReserva_(ServicoGestaoReservas_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CriarReserva_(ServicoGestaoReservas_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServicoGestaoReservas::Stub::SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::frota::RespostaSimularReserva* response) {
  return ::grpc::internal::BlockingUnaryCall< ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SimularReserva_, context, request, response);
}

void ServicoGestaoReservas::Stub::async::SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SimularReserva_, context, request, response, std::move(f));
}

void ServicoGestaoReservas::Stub::async::SimularReserva(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SimularReserva_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>* ServicoGestaoReservas::Stub::PrepareAsyncSimularReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::frota::RespostaSimularReserva, ::frota::RequisicaoSimularReserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SimularReserva_, context, request);
}

::grpc::ClientAsyncResponseReader< ::frota::RespostaSimularReserva>* ServicoGestaoReservas::Stub::AsyncSimularReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoSimularReserva& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSimularReservaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServicoGestaoReservas::Stub::CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::frota::Reserva* response) {
  return ::grpc::internal::BlockingUnaryCall< ::frota::RequisicaoCriarReserva, ::frota::Reserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CriarReserva_, context, request, response);
}

void ServicoGestaoReservas::Stub::async::CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::frota::RequisicaoCriarReserva, ::frota::Reserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarReserva_, context, request, response, std::move(f));
}

void ServicoGestaoReservas::Stub::async::CriarReserva(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CriarReserva_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::frota::Reserva>* ServicoGestaoReservas::Stub::PrepareAsyncCriarReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::frota::Reserva, ::frota::RequisicaoCriarReserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CriarReserva_, context, request);
}

::grpc::ClientAsyncResponseReader< ::frota::Reserva>* ServicoGestaoReservas::Stub::AsyncCriarReservaRaw(::grpc::ClientContext* context, const ::frota::RequisicaoCriarReserva& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCriarReservaRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServicoGestaoReservas::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoGestaoReservas_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoGestaoReservas::Service, ::frota::RequisicaoSimularReserva, ::frota::RespostaSimularReserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoGestaoReservas::Service* service,
             ::grpc::ServerContext* ctx,
             const ::frota::RequisicaoSimularReserva* req,
             ::frota::RespostaSimularReserva* resp) {
               return service->SimularReserva(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServicoGestaoReservas_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServicoGestaoReservas::Service, ::frota::RequisicaoCriarReserva, ::frota::Reserva, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServicoGestaoReservas::Service* service,
             ::grpc::ServerContext* ctx,
             const ::frota::RequisicaoCriarReserva* req,
             ::frota::Reserva* resp) {
               return service->CriarReserva(ctx, req, resp);
             }, this)));
}

ServicoGestaoReservas::Service::~Service() {
}

::grpc::Status ServicoGestaoReservas::Service::SimularReserva(::grpc::ServerContext* context, const ::frota::RequisicaoSimularReserva* request, ::frota::RespostaSimularReserva* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServicoGestaoReservas::Service::CriarReserva(::grpc::ServerContext* context, const ::frota::RequisicaoCriarReserva* request, ::frota::Reserva* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace frota

