// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service-a.proto

#include "service-a.pb.h"
#include "service-a.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace servicea {

static const char* ServiceA_method_names[] = {
  "/servicea.ServiceA/ProcessA",
};

std::unique_ptr< ServiceA::Stub> ServiceA::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServiceA::Stub> stub(new ServiceA::Stub(channel, options));
  return stub;
}

ServiceA::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessA_(ServiceA_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServiceA::Stub::ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::servicea::ResponseA* response) {
  return ::grpc::internal::BlockingUnaryCall< ::servicea::RequestA, ::servicea::ResponseA, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessA_, context, request, response);
}

void ServiceA::Stub::async::ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::servicea::RequestA, ::servicea::ResponseA, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessA_, context, request, response, std::move(f));
}

void ServiceA::Stub::async::ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessA_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>* ServiceA::Stub::PrepareAsyncProcessARaw(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::servicea::ResponseA, ::servicea::RequestA, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessA_, context, request);
}

::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>* ServiceA::Stub::AsyncProcessARaw(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessARaw(context, request, cq);
  result->StartCall();
  return result;
}

ServiceA::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServiceA_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServiceA::Service, ::servicea::RequestA, ::servicea::ResponseA, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServiceA::Service* service,
             ::grpc::ServerContext* ctx,
             const ::servicea::RequestA* req,
             ::servicea::ResponseA* resp) {
               return service->ProcessA(ctx, req, resp);
             }, this)));
}

ServiceA::Service::~Service() {
}

::grpc::Status ServiceA::Service::ProcessA(::grpc::ServerContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace servicea
#include <grpcpp/ports_undef.inc>

