// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service-a.proto
#ifndef GRPC_service_2da_2eproto__INCLUDED
#define GRPC_service_2da_2eproto__INCLUDED

#include "service-a.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace servicea {

// Serviço A - responsável por uma funcionalidade de backend
class ServiceA final {
 public:
  static constexpr char const* service_full_name() {
    return "servicea.ServiceA";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::servicea::ResponseA* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::servicea::ResponseA>> AsyncProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::servicea::ResponseA>>(AsyncProcessARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::servicea::ResponseA>> PrepareAsyncProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::servicea::ResponseA>>(PrepareAsyncProcessARaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::servicea::ResponseA>* AsyncProcessARaw(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::servicea::ResponseA>* PrepareAsyncProcessARaw(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::servicea::ResponseA* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>> AsyncProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>>(AsyncProcessARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>> PrepareAsyncProcessA(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>>(PrepareAsyncProcessARaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response, std::function<void(::grpc::Status)>) override;
      void ProcessA(::grpc::ClientContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>* AsyncProcessARaw(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::servicea::ResponseA>* PrepareAsyncProcessARaw(::grpc::ClientContext* context, const ::servicea::RequestA& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessA_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ProcessA(::grpc::ServerContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessA() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessA(::grpc::ServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessA(::grpc::ServerContext* context, ::servicea::RequestA* request, ::grpc::ServerAsyncResponseWriter< ::servicea::ResponseA>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessA<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessA() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::servicea::RequestA, ::servicea::ResponseA>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::servicea::RequestA* request, ::servicea::ResponseA* response) { return this->ProcessA(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessA(
        ::grpc::MessageAllocator< ::servicea::RequestA, ::servicea::ResponseA>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::servicea::RequestA, ::servicea::ResponseA>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessA(::grpc::ServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessA(
      ::grpc::CallbackServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessA<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessA() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessA(::grpc::ServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessA() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessA(::grpc::ServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessA(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessA() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessA(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessA(::grpc::ServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessA(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessA() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::servicea::RequestA, ::servicea::ResponseA>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::servicea::RequestA, ::servicea::ResponseA>* streamer) {
                       return this->StreamedProcessA(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessA(::grpc::ServerContext* /*context*/, const ::servicea::RequestA* /*request*/, ::servicea::ResponseA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessA(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::servicea::RequestA,::servicea::ResponseA>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessA<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessA<Service > StreamedService;
};

}  // namespace servicea


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_service_2da_2eproto__INCLUDED
