// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service-a.proto
// Protobuf C++ Version: 6.33.5

#include "service-a.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace servicea {
template <typename>
PROTOBUF_CONSTEXPR ResponseA_ResultEntry_DoNotUse::ResponseA_ResultEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ResponseA_ResultEntry_DoNotUse::MapEntry(ResponseA_ResultEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ResponseA_ResultEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct ResponseA_ResultEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseA_ResultEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseA_ResultEntry_DoNotUseDefaultTypeInternal() {}
  union {
    ResponseA_ResultEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseA_ResultEntry_DoNotUseDefaultTypeInternal _ResponseA_ResultEntry_DoNotUse_default_instance_;

inline constexpr RequestA::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RequestA::RequestA(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RequestA_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestADefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestADefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestADefaultTypeInternal() {}
  union {
    RequestA _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestADefaultTypeInternal _RequestA_default_instance_;

inline constexpr ResponseA::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{0},
        result_{} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseA::ResponseA(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ResponseA_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResponseADefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseADefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseADefaultTypeInternal() {}
  union {
    ResponseA _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseADefaultTypeInternal _ResponseA_default_instance_;
}  // namespace servicea
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_service_2da_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_service_2da_2eproto = nullptr;
const ::uint32_t
    TableStruct_service_2da_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::servicea::RequestA, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::servicea::RequestA, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::servicea::RequestA, _impl_.payload_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::servicea::ResponseA_ResultEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::servicea::ResponseA_ResultEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::servicea::ResponseA_ResultEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::servicea::ResponseA, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::servicea::ResponseA, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::servicea::ResponseA, _impl_.result_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::servicea::RequestA)},
        {7, sizeof(::servicea::ResponseA_ResultEntry_DoNotUse)},
        {14, sizeof(::servicea::ResponseA)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::servicea::_RequestA_default_instance_._instance,
    &::servicea::_ResponseA_ResultEntry_DoNotUse_default_instance_._instance,
    &::servicea::_ResponseA_default_instance_._instance,
};
const char descriptor_table_protodef_service_2da_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017service-a.proto\022\010servicea\"+\n\010RequestA\022"
    "\016\n\006userId\030\001 \001(\t\022\017\n\007payload\030\002 \001(\t\"{\n\tResp"
    "onseA\022\016\n\006status\030\001 \001(\005\022/\n\006result\030\002 \003(\0132\037."
    "servicea.ResponseA.ResultEntry\032-\n\013Result"
    "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\0012\?\n"
    "\010ServiceA\0223\n\010ProcessA\022\022.servicea.Request"
    "A\032\023.servicea.ResponseAb\006proto3"
};
static ::absl::once_flag descriptor_table_service_2da_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_service_2da_2eproto = {
    false,
    false,
    270,
    descriptor_table_protodef_service_2da_2eproto,
    "service-a.proto",
    &descriptor_table_service_2da_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_service_2da_2eproto::offsets,
    file_level_enum_descriptors_service_2da_2eproto,
    file_level_service_descriptors_service_2da_2eproto,
};
namespace servicea {
// ===================================================================

class RequestA::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RequestA>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RequestA, _impl_._has_bits_);
};

RequestA::RequestA(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RequestA_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:servicea.RequestA)
}
PROTOBUF_NDEBUG_INLINE RequestA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::servicea::RequestA& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        userid_(arena, from.userid_),
        payload_(arena, from.payload_) {}

RequestA::RequestA(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RequestA& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RequestA_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestA* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:servicea.RequestA)
}
PROTOBUF_NDEBUG_INLINE RequestA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        userid_(arena),
        payload_(arena) {}

inline void RequestA::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestA::~RequestA() {
  // @@protoc_insertion_point(destructor:servicea.RequestA)
  SharedDtor(*this);
}
inline void RequestA::SharedDtor(MessageLite& self) {
  RequestA& this_ = static_cast<RequestA&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.userid_.Destroy();
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RequestA::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RequestA(arena);
}
constexpr auto RequestA::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RequestA),
                                            alignof(RequestA));
}
constexpr auto RequestA::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RequestA_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RequestA::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RequestA>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RequestA::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RequestA>(), &RequestA::ByteSizeLong,
              &RequestA::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RequestA, _impl_._cached_size_),
          false,
      },
      &RequestA::kDescriptorMethods,
      &descriptor_table_service_2da_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RequestA_class_data_ =
        RequestA::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RequestA::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RequestA_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RequestA_class_data_.tc_table);
  return RequestA_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2>
RequestA::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RequestA, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RequestA_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::servicea::RequestA>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string payload = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RequestA, _impl_.payload_)}},
    // string userId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RequestA, _impl_.userid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userId = 1;
    {PROTOBUF_FIELD_OFFSET(RequestA, _impl_.userid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string payload = 2;
    {PROTOBUF_FIELD_OFFSET(RequestA, _impl_.payload_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\6\7\0\0\0\0\0"
    "servicea.RequestA"
    "userId"
    "payload"
  }},
};
PROTOBUF_NOINLINE void RequestA::Clear() {
// @@protoc_insertion_point(message_clear_start:servicea.RequestA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.userid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.payload_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RequestA::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RequestA& this_ = static_cast<const RequestA&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RequestA::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RequestA& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:servicea.RequestA)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string userId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_userid().empty()) {
      const ::std::string& _s = this_._internal_userid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "servicea.RequestA.userId");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string payload = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_payload().empty()) {
      const ::std::string& _s = this_._internal_payload();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "servicea.RequestA.payload");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:servicea.RequestA)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RequestA::ByteSizeLong(const MessageLite& base) {
  const RequestA& this_ = static_cast<const RequestA&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RequestA::ByteSizeLong() const {
  const RequestA& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:servicea.RequestA)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string userId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_userid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_userid());
      }
    }
    // string payload = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_payload());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RequestA::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RequestA*>(&to_msg);
  auto& from = static_cast<const RequestA&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:servicea.RequestA)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_userid().empty()) {
        _this->_internal_set_userid(from._internal_userid());
      } else {
        if (_this->_impl_.userid_.IsDefault()) {
          _this->_internal_set_userid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_payload().empty()) {
        _this->_internal_set_payload(from._internal_payload());
      } else {
        if (_this->_impl_.payload_.IsDefault()) {
          _this->_internal_set_payload("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RequestA::CopyFrom(const RequestA& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:servicea.RequestA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestA::InternalSwap(RequestA* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
}

::google::protobuf::Metadata RequestA::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
ResponseA_ResultEntry_DoNotUse::ResponseA_ResultEntry_DoNotUse()
    : SuperType(ResponseA_ResultEntry_DoNotUse_class_data_.base()) {}
ResponseA_ResultEntry_DoNotUse::ResponseA_ResultEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, ResponseA_ResultEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
ResponseA_ResultEntry_DoNotUse::ResponseA_ResultEntry_DoNotUse() : SuperType() {}
ResponseA_ResultEntry_DoNotUse::ResponseA_ResultEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL ResponseA_ResultEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ResponseA_ResultEntry_DoNotUse(arena);
}
constexpr auto ResponseA_ResultEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResponseA_ResultEntry_DoNotUse),
                                            alignof(ResponseA_ResultEntry_DoNotUse));
}
constexpr auto ResponseA_ResultEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ResponseA_ResultEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ResponseA_ResultEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ResponseA_ResultEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ResponseA_ResultEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&ResponseA_ResultEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ResponseA_ResultEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &ResponseA_ResultEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_service_2da_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ResponseA_ResultEntry_DoNotUse_class_data_ =
        ResponseA_ResultEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ResponseA_ResultEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ResponseA_ResultEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ResponseA_ResultEntry_DoNotUse_class_data_.tc_table);
  return ResponseA_ResultEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2>
ResponseA_ResultEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResponseA_ResultEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ResponseA_ResultEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::servicea::ResponseA_ResultEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponseA_ResultEntry_DoNotUse, _impl_.value_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(ResponseA_ResultEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ResponseA_ResultEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseA_ResultEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseA_ResultEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\36\3\0\0\0\0\0\0"
    "servicea.ResponseA.ResultEntry"
    "key"
  }},
};
// ===================================================================

class ResponseA::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ResponseA>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ResponseA, _impl_._has_bits_);
};

ResponseA::ResponseA(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResponseA_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:servicea.ResponseA)
}
PROTOBUF_NDEBUG_INLINE ResponseA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::servicea::ResponseA& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        result_{visibility, arena, from.result_} {}

ResponseA::ResponseA(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ResponseA& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResponseA_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResponseA* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:servicea.ResponseA)
}
PROTOBUF_NDEBUG_INLINE ResponseA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        result_{visibility, arena} {}

inline void ResponseA::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
ResponseA::~ResponseA() {
  // @@protoc_insertion_point(destructor:servicea.ResponseA)
  SharedDtor(*this);
}
inline void ResponseA::SharedDtor(MessageLite& self) {
  ResponseA& this_ = static_cast<ResponseA&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ResponseA::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ResponseA(arena);
}
constexpr auto ResponseA::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ResponseA, _impl_.result_) +
          decltype(ResponseA::_impl_.result_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ResponseA), alignof(ResponseA), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ResponseA::PlacementNew_,
                                 sizeof(ResponseA),
                                 alignof(ResponseA));
  }
}
constexpr auto ResponseA::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ResponseA_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ResponseA::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ResponseA>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ResponseA::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ResponseA>(), &ResponseA::ByteSizeLong,
              &ResponseA::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ResponseA, _impl_._cached_size_),
          false,
      },
      &ResponseA::kDescriptorMethods,
      &descriptor_table_service_2da_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ResponseA_class_data_ =
        ResponseA::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ResponseA::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ResponseA_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ResponseA_class_data_.tc_table);
  return ResponseA_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 33, 2>
ResponseA::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResponseA, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ResponseA_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::servicea::ResponseA>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponseA, _impl_.status_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(ResponseA, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 status = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseA, _impl_.status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // map<string, int32> result = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseA, _impl_.result_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(
          1, 0, 9, 5, 0)},
  }},
  {{
    "\22\0\6\0\0\0\0\0"
    "servicea.ResponseA"
    "result"
  }},
};
PROTOBUF_NOINLINE void ResponseA::Clear() {
// @@protoc_insertion_point(message_clear_start:servicea.ResponseA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    _impl_.status_ = 0;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.result_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ResponseA::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ResponseA& this_ = static_cast<const ResponseA&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ResponseA::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ResponseA& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:servicea.ResponseA)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 status = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_status() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_status(), target);
    }
  }

  // map<string, int32> result = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_result().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::int32_t>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::int32_t,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_INT32>;
      const auto& field = this_._internal_result();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "servicea.ResponseA.result");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "servicea.ResponseA.result");
        }
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:servicea.ResponseA)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ResponseA::ByteSizeLong(const MessageLite& base) {
  const ResponseA& this_ = static_cast<const ResponseA&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ResponseA::ByteSizeLong() const {
  const ResponseA& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:servicea.ResponseA)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int32 status = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_status() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_status());
      }
    }
    // map<string, int32> result = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_result_size());
      for (const auto& entry : this_._internal_result()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::int32_t,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ResponseA::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ResponseA*>(&to_msg);
  auto& from = static_cast<const ResponseA&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:servicea.ResponseA)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_impl_.result_.MergeFrom(from._impl_.result_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ResponseA::CopyFrom(const ResponseA& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:servicea.ResponseA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResponseA::InternalSwap(ResponseA* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.status_, other->_impl_.status_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
}

::google::protobuf::Metadata ResponseA::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace servicea
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_service_2da_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
