# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contratos_grpc import autenticacao_pb2 as contratos__grpc_dot_autenticacao__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contratos_grpc/autenticacao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoAutenticacaoStub:
    """SERVIÇOS gRPC (Princípio de Responsabilidade Única aplicado na Rede)

    Responsável estritamente pela validação de credenciais e geração/verificação de JWT
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/autenticacao.ServicoAutenticacao/Login',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoLogin.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.RespostaToken.FromString,
                _registered_method=True)
        self.ValidarToken = channel.unary_unary(
                '/autenticacao.ServicoAutenticacao/ValidarToken',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoValidarToken.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.RespostaValidacao.FromString,
                _registered_method=True)


class ServicoAutenticacaoServicer:
    """SERVIÇOS gRPC (Princípio de Responsabilidade Única aplicado na Rede)

    Responsável estritamente pela validação de credenciais e geração/verificação de JWT
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidarToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoAutenticacaoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoLogin.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.RespostaToken.SerializeToString,
            ),
            'ValidarToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidarToken,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoValidarToken.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.RespostaValidacao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autenticacao.ServicoAutenticacao', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autenticacao.ServicoAutenticacao', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoAutenticacao:
    """SERVIÇOS gRPC (Princípio de Responsabilidade Única aplicado na Rede)

    Responsável estritamente pela validação de credenciais e geração/verificação de JWT
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoAutenticacao/Login',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoLogin.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.RespostaToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidarToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoAutenticacao/ValidarToken',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoValidarToken.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.RespostaValidacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServicoFuncionarioStub:
    """Responsável pela gestão interna do sistema
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarFuncionario = channel.unary_unary(
                '/autenticacao.ServicoFuncionario/CriarFuncionario',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarFuncionario.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.Funcionario.FromString,
                _registered_method=True)
        self.ObterFuncionario = channel.unary_unary(
                '/autenticacao.ServicoFuncionario/ObterFuncionario',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.Funcionario.FromString,
                _registered_method=True)


class ServicoFuncionarioServicer:
    """Responsável pela gestão interna do sistema
    """

    def CriarFuncionario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterFuncionario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoFuncionarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarFuncionario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarFuncionario,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarFuncionario.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.Funcionario.SerializeToString,
            ),
            'ObterFuncionario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterFuncionario,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.Funcionario.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autenticacao.ServicoFuncionario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autenticacao.ServicoFuncionario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoFuncionario:
    """Responsável pela gestão interna do sistema
    """

    @staticmethod
    def CriarFuncionario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoFuncionario/CriarFuncionario',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarFuncionario.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.Funcionario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterFuncionario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoFuncionario/ObterFuncionario',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.Funcionario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServicoClienteStub:
    """Responsável pelo ecossistema de clientes e relações empresariais
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarPessoaFisica = channel.unary_unary(
                '/autenticacao.ServicoCliente/CriarPessoaFisica',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarPessoaFisica.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.PessoaFisica.FromString,
                _registered_method=True)
        self.CriarPessoaJuridica = channel.unary_unary(
                '/autenticacao.ServicoCliente/CriarPessoaJuridica',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarPessoaJuridica.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.FromString,
                _registered_method=True)
        self.ObterPessoaFisica = channel.unary_unary(
                '/autenticacao.ServicoCliente/ObterPessoaFisica',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.PessoaFisica.FromString,
                _registered_method=True)
        self.ObterPessoaJuridica = channel.unary_unary(
                '/autenticacao.ServicoCliente/ObterPessoaJuridica',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.FromString,
                _registered_method=True)
        self.AssociarMotorista = channel.unary_unary(
                '/autenticacao.ServicoCliente/AssociarMotorista',
                request_serializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoAssociarMotorista.SerializeToString,
                response_deserializer=contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.FromString,
                _registered_method=True)


class ServicoClienteServicer:
    """Responsável pelo ecossistema de clientes e relações empresariais
    """

    def CriarPessoaFisica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarPessoaJuridica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterPessoaFisica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterPessoaJuridica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssociarMotorista(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoClienteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarPessoaFisica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPessoaFisica,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarPessoaFisica.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.PessoaFisica.SerializeToString,
            ),
            'CriarPessoaJuridica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPessoaJuridica,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarPessoaJuridica.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.SerializeToString,
            ),
            'ObterPessoaFisica': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterPessoaFisica,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.PessoaFisica.SerializeToString,
            ),
            'ObterPessoaJuridica': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterPessoaJuridica,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.SerializeToString,
            ),
            'AssociarMotorista': grpc.unary_unary_rpc_method_handler(
                    servicer.AssociarMotorista,
                    request_deserializer=contratos__grpc_dot_autenticacao__pb2.RequisicaoAssociarMotorista.FromString,
                    response_serializer=contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autenticacao.ServicoCliente', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autenticacao.ServicoCliente', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoCliente:
    """Responsável pelo ecossistema de clientes e relações empresariais
    """

    @staticmethod
    def CriarPessoaFisica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoCliente/CriarPessoaFisica',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarPessoaFisica.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.PessoaFisica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarPessoaJuridica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoCliente/CriarPessoaJuridica',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoCriarPessoaJuridica.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterPessoaFisica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoCliente/ObterPessoaFisica',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.PessoaFisica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterPessoaJuridica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoCliente/ObterPessoaJuridica',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoObterPorId.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssociarMotorista(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.ServicoCliente/AssociarMotorista',
            contratos__grpc_dot_autenticacao__pb2.RequisicaoAssociarMotorista.SerializeToString,
            contratos__grpc_dot_autenticacao__pb2.PessoaJuridica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
